import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const key = process.env.OPENROUTER_API_KEY;
    if (!key) {
      return NextResponse.json({ error: 'OPENROUTER_API_KEY is not configured' }, { status: 500 });
    }

    let customPrompt = '';
    try {
      const body = await request.json();
      customPrompt = body?.prompt || '';
    } catch {
      // Prompt optional
    }

    const prompt =
      customPrompt.trim() ||
      'Photorealistic vertical portrait of a charismatic professional corporate office presenter in a sleek modern tech office, looking directly into the camera with a confident friendly smile, natural studio lighting, ultra sharp focus, cinematic UGC creator style, 8k resolution.';

    const model = process.env.OPENROUTER_IMAGE_MODEL || 'openai/gpt-5-image-mini';

    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${key}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://github.com/swikritik63/syncflow-ai',
        'X-Title': 'SyncFlow AI',
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      return NextResponse.json(
        { error: `OpenRouter API error: ${response.status}`, details: errText },
        { status: response.status }
      );
    }

    const data = await response.json();
    const images = data.choices?.[0]?.message?.images;
    const imageUrl = images?.[0]?.image_url?.url || '';

    if (!imageUrl) {
      return NextResponse.json({ error: 'No image generated by OpenRouter', raw: data }, { status: 502 });
    }

    return NextResponse.json({
      success: true,
      imageUrl,
      model,
      prompt,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
